/*
 * AddSubjectViewInner.java
 *
 * Created on __DATE__, __TIME__
 */

package org.lanqiao.view;

import org.lanqiao.dbutil.YockDBUtil;

import javax.swing.*;

/**
 *
 * @author  __USER__
 */
public class AddSubjectViewInner extends javax.swing.JInternalFrame {

	/** Creates new form AddSubjectViewInner */
	public AddSubjectViewInner() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		label1 = new java.awt.Label();
		bt_add = new javax.swing.JButton();
		te_add = new javax.swing.JTextField();

		label1.setFont(new java.awt.Font("Dialog", 0, 30));
		label1.setText("\u6dfb\u52a0\u79d1\u76ee\u7cfb\u7edf");

		bt_add.setText("jButton1");
		bt_add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_addActionPerformed(evt);
			}
		});

		te_add.setText("jTextField1");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(179,
																		179,
																		179)
																.addComponent(
																		label1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(94, 94,
																		94)
																.addComponent(
																		bt_add)
																.addGap(42, 42,
																		42)
																.addComponent(
																		te_add,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		195,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(146, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(28, 28, 28)
								.addComponent(label1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(71, 71, 71)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(bt_add)
												.addComponent(
														te_add,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(143, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
/**
 * 点击添加事件
 * @param evt
 */
	private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String ad_calss = te_add.getText();
		String sql = "INSERT INTO TB_SUBJECT(SUBJECT_ID,SUBJECT_NAME) "
				+ "VALUES(SQ_SUBJECT.nextval,?)";
		YockDBUtil.executeDML(sql, ad_calss);
		JOptionPane.showMessageDialog(null, "添加成功");
		
		
		
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton bt_add;
	private java.awt.Label label1;
	private javax.swing.JTextField te_add;
	// End of variables declaration//GEN-END:variables

}