/*
 * HomeView.java
 *
 * Created on __DATE__, __TIME__
 */

package org.lanqiao.view;

import org.lanqiao.dbutil.YockDBUtil;

/**
 *
 * @author  __USER__
 */
public class HomeView extends javax.swing.JFrame {

	/** Creates new form HomeView */
	public HomeView() {
		initComponents();

		//设置窗口居中
		this.setLocationRelativeTo(null);
		//禁用拉伸窗口
		//this.setResizable(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		dp_table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		mi_addclass = new javax.swing.JMenuItem();
		mi_selectclass = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		mi_selectsubject = new javax.swing.JRadioButtonMenuItem();
		mi_addsubject = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();
		dropout = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u5458\u7ba1\u7406\u7cfb\u7edf\u4e3b\u9875");

		jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/org/lanqiao/imgs/姓名.png"))); // NOI18N
		jMenu1.setText("\u73ed\u7ea7\u4fe1\u606f\u7ba1\u7406");

		mi_addclass.setText("\u6dfb\u52a0\u73ed\u7ea7");
		mi_addclass.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mi_addclassActionPerformed(evt);
			}
		});
		jMenu1.add(mi_addclass);

		mi_selectclass.setText("\u67e5\u8be2\u73ed\u7ea7");
		mi_selectclass.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mi_selectclassActionPerformed(evt);
			}
		});
		jMenu1.add(mi_selectclass);

		jMenuBar1.add(jMenu1);

		jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/org/lanqiao/imgs/科目管理.png"))); // NOI18N
		jMenu2.setText("\u79d1\u76ee\u4fe1\u606f\u7ba1\u7406");

		mi_selectsubject.setSelected(true);
		mi_selectsubject.setText("\u67e5\u8be2\u79d1\u76ee");
		mi_selectsubject.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mi_selectsubjectActionPerformed(evt);
			}
		});
		jMenu2.add(mi_selectsubject);

		mi_addsubject.setText("\u6dfb\u52a0\u79d1\u76ee");
		mi_addsubject.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mi_addsubjectActionPerformed(evt);
			}
		});
		jMenu2.add(mi_addsubject);

		jMenuBar1.add(jMenu2);
		jMenuBar1.add(jMenu3);

		jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/org/lanqiao/imgs/积分.png"))); // NOI18N
		jMenu4.setText("\u79ef\u5206\u4fe1\u606f\u7ba1\u7406");
		jMenuBar1.add(jMenu4);

		dropout.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/org/lanqiao/imgs/退出.png"))); // NOI18N
		dropout.setText("\u9000\u51fa");
		dropout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				dropoutMouseDragged(evt);
			}
		});
		dropout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dropoutActionPerformed(evt);
			}
		});
		jMenuBar1.add(dropout);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				dp_table, javax.swing.GroupLayout.DEFAULT_SIZE, 656,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				dp_table, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**
	 * 鼠标点击菜单退出事件
	 * @param evt
	 */
	private void dropoutMouseDragged(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	}

	/**
	 * 点击菜单退出事件
	 * @param evt
	 */
	private void dropoutActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
		setVisible(false);

	}

	/**
	 * 点击菜单添加科目事件
	 * @param evt
	 */
	private void mi_addsubjectActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		AddSubjectViewInner viewInner = new AddSubjectViewInner();
		viewInner.setVisible(true);
		dp_table.add(viewInner);
	}

	/**
	 * 点击菜单查询科目事件
	 * @param evt
	 */
	private void mi_selectsubjectActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		SelectSubjectViewInner2 viewInner = new SelectSubjectViewInner2();
		viewInner.setVisible(true);

		dp_table.add(viewInner);
	}

	/**
	 * 查询班级菜单项点击事件
	 * @param evt
	 */
	private void mi_selectclassActionPerformed(java.awt.event.ActionEvent evt) {
		SelectClassViewInner viewInner = new SelectClassViewInner();
		viewInner.setVisible(true);

		//将窗口添加至桌面容器中显示
		dp_table.add(viewInner);
	}

	/**
	 * 添加班级菜单项点击事件
	 * @param evt
	 */
	private void mi_addclassActionPerformed(java.awt.event.ActionEvent evt) {
		AddClassViewInner2 viewInner = new AddClassViewInner2();
		viewInner.setVisible(true);

		//将窗口添加至桌面容器中显示
		dp_table.add(viewInner);

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomeView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JDesktopPane dp_table;
	private javax.swing.JMenu dropout;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem mi_addclass;
	private javax.swing.JMenuItem mi_addsubject;
	private javax.swing.JMenuItem mi_selectclass;
	private javax.swing.JRadioButtonMenuItem mi_selectsubject;
	// End of variables declaration//GEN-END:variables

}